version: '3'

services:
  backend:
    build:
      context: ./jobscontrol
    ports:
      - "5000:5000"
    volumes:
      - ./jobscontrol:/app
      - /app/.venv
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development