[project]
name = "jobscontrol"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn>=0.34.0",
    "pylint>=3.3.0",
    "pyproject-toml>=0.0.10",
    "pytest>=8.3.3",
    "ruff>=0.6.6",
    "sqlalchemy>=2.0.35",
    "uvicorn>=0.34.0",
    "black>=25.1.0",
    "authlib>=1.5.2",
    "python-jose>=3.4.0",
    "httpx>=0.28.1",
    "dotenv>=0.9.9",
    "itsdangerous>=2.2.0",
    "bcrypt>=4.3.0",
    "passlib>=1.7.4",
]

[tool.ruff]
line-length = 88
extend-exclude = ['migrations', 'tests', 'docs', 'build', 'dist']
exclude = [".venv"]

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT', 'C', 'N']
ignore = ['E501']

[tool.ruff.format]
preview = true
quote-style = 'single'
